### ISSUE TITLE
Suggestion: enable "position" parameter in slick-greeter-conf to position login box

### ISSUE THREAD

**Issue by Earthling-Z3R0** [linuxmint/slick-greeter#201] opened 2022-04-02 09:14 UTC
Please enable "position" parameter in slick-greeter-conf to position login box.

**Comment by Roshanpaudel111** [comment] 2023-01-20 02:16
yes

**Comment by maloosheck** [comment] 2023-08-23 01:32
One more kind request for implementing "position" parameter in slick-greeter. Thank you.

**Comment by leigh123linux** [comment] 2023-08-23 06:47
Duplicate of https://github.com/linuxmint/slick-greeter/issues/92

**Closed by leigh123linux** 2023-08-23 06:47 UTC
