### ISSUE TITLE
[Change Request] - Show User Avatar

### ISSUE THREAD

**Issue by memoryleakx** [linuxmint/slick-greeter#81] opened 2017-11-13 10:55 UTC
Hi Folks,
It would be nice if you could display the avatar from the selected user.
You can find the avatar in the **LightDM.User -> get_image()** property.
https://lazka.github.io/pgi-docs/LightDM-1/classes/User.html#LightDM.User.get_image

# Example:
![alt text](https://pre08.deviantart.net/92e4/th/pre/i/2012/033/8/f/unity_greeter_lock_screen_by_fverdeja93-d4ogdwt.png "Greeter with User Avatar")

**Comment by fossfreedom** [comment] 2017-11-19 11:23
this is a duplicate of this issue https://github.com/linuxmint/slick-greeter/issues/47

**Closed** 2017-11-19 20:34 UTC
