### ISSUE TITLE
Password field for standard user login is not shown

### ISSUE THREAD

**Issue by bamaboy9** [linuxmint/slick-greeter#191] opened 2021-08-30 21:14 UTC
```
 * Cinnamon version 5.0.5
   - I am not using the daily builds PPA.  This is my first submittal on Github.
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 20.2)
 * Graphics hardware *and* driver used: 
bill@TECRA-A11:~$ lspci | grep "VGA"
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 02)
bill@TECRA-A11:~$ 

bill@TECRA-A11:~$ inxi -Gx
Graphics:
  Device-1: Intel Core Processor Integrated Graphics vendor: Toshiba 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.11 driver: intel resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics (ILK) v: 2.1 Mesa 21.0.3 
  direct render: Yes 
bill@TECRA-A11:~$ 

 * 64 bit
 * What theme/applets are you using?
        Answer:  GTK Theme:  Mint-X
	Icon Theme:  Mint-X-Dark
	Mouse cursor:  DMZ-White

 * Attach ~/.xsession-errors, or /var/log/syslog
 ```
/home/bill/.xsession-errors:
`dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/bill/.Xauthority
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting LANGUAGE=en_US
dbus-update-activation-environment: setting DESKTOP_SESSION=cinnamon
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting PWD=/home/bill
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=cinnamon
dbus-update-activation-environment: setting LOGNAME=bill
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting XAUTHORITY=/home/bill/.Xauthority
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/bill
dbus-update-activation-environment: setting GDM_LANG=en_US
dbus-update-activation-environment: setting HOME=/home/bill
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting USER=bill
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting SHLVL=1
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting GTK3_MODULES=xapp-gtk3-module
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/bill/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
dbus-update-activation-environment: setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
dbus-update-activation-environment: setting GDMSESSION=cinnamon
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment
** Message: 12:09:24.321: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
** Message: 12:09:24.322: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
** Message: 12:09:24.323: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
** Message: 12:09:26.537: Existing monitor config (/home/bill/.config/cinnamon-monitors.xml) not found at startup. Looking for legacy configuration (monitors.xml)
Cjs-Message: 12:09:31.811: Profiler is disabled. Not setting up signals.
Clutter-Message: 12:09:32.291: Sync method: PRESENTATION TIME

(nm-applet:1310): libnotify-WARNING **: 12:09:35.070: Failed to connect to proxy

(nm-applet:1310): nm-applet-WARNING **: 12:09:35.072: Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.Notifications” on object at path /org/freedesktop/Notifications
Cjs-Message: 12:09:39.701: JS LOG: About to start Cinnamon
** Message: 12:09:42.566: nemo-desktop: session is cinnamon, establishing proxy
cinnamon-session[954]: WARNING: t+20.29023s: Detected that screensaver has appeared on the bus
qt5ct: using qt5ct plugin
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/cryptography.hazmat.bindings._openssl.cpython-38-x86_64-linux-gnu.so'
Cjs-Message: 12:09:48.849: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 9059 ms
Cjs-Message: 12:09:48.889: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Linux Mint/cinnamon/cinnamon.css
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/cryptography.hazmat.bindings._padding.cpython-38-x86_64-linux-gnu.so'
Cjs-Message: 12:09:49.037: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Linux Mint/cinnamon
qt5ct: D-Bus system tray: no
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/psutil._psutil_linux.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/psutil._psutil_posix.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/apex._apex.cpython-38-x86_64-linux-gnu.so'
Cjs-Message: 12:09:50.259: JS LOG: [LookingGlass/info] loaded at Tue Aug 31 2021 12:09:49 GMT-0500 (Central Daylight Time)
Cjs-Message: 12:09:50.260: JS LOG: Cinnamon started at Tue Aug 31 2021 12:09:49 GMT-0500 (Central Daylight Time)
Cjs-Message: 12:09:50.667: JS LOG: [LookingGlass/info] ExtensionSystem started in 2 ms
Cjs-Message: 12:09:50.668: JS LOG: [LookingGlass/info] NaNms
Cjs-Message: 12:09:50.668: JS LOG: [LookingGlass/info] SearchProviderManager started in 2 ms
openGL version 2.1 Mesa 21 detected (GL Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
St-Message: 12:09:51.211: cogl npot texture sizes SUPPORTED
Cjs-Message: 12:09:51.483: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 139 ms
Cjs-Message: 12:09:51.492: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 12:09:51.502: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 18 ms
Cjs-Message: 12:09:51.540: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 38 ms
Cjs-Message: 12:09:51.676: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 12:09:51.733: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 193 ms
Cjs-Message: 12:09:51.776: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 43 ms
Cjs-Message: 12:09:52.041: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 265 ms
Cjs-Message: 12:09:52.097: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 12:09:52.110: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 69 ms
Cjs-Message: 12:09:52.229: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 119 ms
Cjs-Message: 12:09:52.421: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 191 ms
Cjs-Message: 12:09:52.612: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 190 ms
Cjs-Message: 12:09:52.623: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 10 ms
Cinnamon warning: Log level 16: cinnamon tray: icon app window is gone
Cjs-Message: 12:09:52.703: JS LOG: [LookingGlass/info] Adding systray: unknown (24x24px)
Cjs-Message: 12:09:52.705: JS LOG: [LookingGlass/info] Resized unknown with normalized size (24x24px)
Cinnamon warning: Log level 16: cinnamon tray: icon app window is gone
Cjs-Message: 12:09:52.914: JS LOG: [LookingGlass/info] Adding systray: unknown (24x24px)
Cjs-Message: 12:09:52.915: JS LOG: [LookingGlass/info] Resized unknown with normalized size (24x24px)
Cinnamon warning: Log level 16: cinnamon tray: icon app window is gone
Cjs-Message: 12:09:52.917: JS LOG: [LookingGlass/info] Adding systray: unknown (24x24px)
Cjs-Message: 12:09:52.918: JS LOG: [LookingGlass/info] Resized unknown with normalized size (24x24px)
Cinnamon warning: Log level 16: cinnamon tray: icon app window is gone
Cjs-Message: 12:09:52.919: JS LOG: [LookingGlass/info] Adding systray: unknown (24x24px)
Cjs-Message: 12:09:52.919: JS LOG: [LookingGlass/info] Resized unknown with normalized size (24x24px)
Cjs-Message: 12:09:52.935: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 312 ms
Cjs-Message: 12:09:53.222: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 287 ms
Cjs-Message: 12:09:53.251: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet
Cjs-Message: 12:09:53.252: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueberry (:1.61/org/x/StatusIcon/Icon)

** (csd-power:1102): CRITICAL **: 12:09:53.304: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 12:09:53.399: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 176 ms
Cjs-Message: 12:09:53.626: JS LOG: Unknown network device type, is 14
Cjs-Message: 12:09:53.666: JS LOG: Unknown network device type, is 30
Cjs-Message: 12:09:54.115: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 716 ms
Cjs-Message: 12:09:54.116: JS LOG: [LookingGlass/info] AppletManager started in 3855 ms
Cjs-Message: 12:09:54.216: JS LOG: [LookingGlass/info] Cinnamon took 14515 ms to start
cinnamon-session[954]: WARNING: t+30.28907s: Detected that screensaver has left the bus
Cjs-Message: 12:09:54.490: JS LOG: [LookingGlass/info] Adding systray: hp-systray (24x24px)
Cjs-Message: 12:09:54.490: JS LOG: [LookingGlass/info] Resized hp-systray with normalized size (24x24px)
Cjs-Message: 12:09:59.373: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (:1.78/org/x/StatusIcon/Icon)
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/tornado.speedups.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/wrapt._wrappers.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/PyQt5.QtWidgets.cpython-38-x86_64-linux-gnu.so'
Cjs-Message: 12:10:14.196: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (:1.84/org/x/StatusIcon/Icon)
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/PyQt5.QtCore.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/PyQt5.QtGui.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/bill/.dropbox-dist/dropbox-lnx.x86_64-129.4.3571/PyQt5.QtDBus.cpython-38-x86_64-linux-gnu.so'
Cjs-Message: 12:10:18.170: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: :1.86 (:1.48/org/x/StatusIcon/Icon)
Cjs-Message: 12:12:03.723: JS LOG: [LookingGlass/info] Adding systray: unknown (24x24px)
Cjs-Message: 12:12:03.724: JS LOG: [LookingGlass/info] Resized unknown with normalized size (24x24px)
Cinnamon warning: Invalid WM_TRANSIENT_FOR window 0x520005b specified for 0x5200191 (KeePass).
Cinnamon warning: Window 0x520071e (Options) sets an MWM hint indicating it isn't resizable, but sets min size 104 x 1 and max size 782 x 579; this doesn't make much sense.`

**Issue**
Password field for standard user login is not shown

**Steps to reproduce**
64-bit computer must be running Linux Mint v20.2 and Cinnamon 5.05.  In settings, add one user with standard privileges.  In Settings>Login Window>Users, set the administrator’s username to log in automatically with a Delay before connection of 0.  Reboot the computer.  When it comes up to the administrator’s desktop, in the system tray, click on the Update Manager symbol.  When the Update Manager dialog comes up, click on Refresh.  Install any available updates.  (I installed grub2 bootloader.)  Then, close the update manager dialog box when it has finished installing updates.  Then, click on Menu>Logout>Log Out.  Notice that only the name of the standard user is displayed; the field for entering the standard user’s password is not shown.  But if the cursor is moved to where the password field should be, then the cursor changes...indicating that the field is there...however the field is not displayed.  (See pictures.)  The standard user’s password field will be displayed if I first click on the administrator’s login name and then click on the standard user’s name.

**Expected behaviour**
I expected to see a dialog with both the name of the standard user and the password field.

**Other information**
Only the standard user’s name was displayed.  The standard user’s password field was not displayed.

The problem happens consistently.  (The problem does not happen if don’t run the update manager.)

```
/home/bill/Downloads/Cinnamon Problem/Possible Bug in Cinnamon.odt


```

**Comment by LinuxOnTheDesktop** [comment] 2021-12-03 01:16
This is a duplicate of #153.

**Closed** 2021-12-03 07:29 UTC
