### ISSUE TITLE
username field not displayed well

### ISSUE THREAD

**Issue by eoli3n** [linuxmint/slick-greeter#115] opened 2018-08-28 13:21 UTC
```
 * slick-greeter version 1.1.4
 * Distribution - Ubuntu 18.04
 * Graphics hardware *and* driver used : 800 nodes... mixed but Intel chipset mostly
 * 64 bit
 ```

**Issue**

When lightdm starts, sometimes on some hosts, it half displays ``username`` field when mixing local account and ldap user field.

- When it starts without touching anything
![bug](https://ptpb.pw/v6VG.png)

- Then press ``Up`` arrow
![bug2](https://ptpb.pw/F21A.png)

- And press ``Down`` arrow
![bug3](https://ptpb.pw/dmmt.png)

If i connect a session then disconnect with ctrl + alt +backspace with qxl driver, i always have this (which is not exactly the same as the first screen... bottom border is round.
![bug4](https://ptpb.pw/9ncQ.png)

**Steps to reproduce**

Here my conf files

``slick-greeter.conf ``
```
[Greeter]
background=/usr/share/backgrounds/slick.jpg
draw-user-backgrounds=false
draw-grid=false
show-keyboard=false
show-hostname=true
show-power=true
show-clock=true
show-quit=true
show-a11y=false
activate-numlock=true
theme-name=Ambiance
logo=/usr/share/backgrounds/slick-logo.png
group-filter=groupname
```

``lightdm.conf.d/10-xubuntu.conf``
```
[SeatDefaults]
greeter-session=slick-greeter
user-session=xubuntu
greeter-show-manual-login=true
allow-guest=false
greeter-hide-users=false
display-setup-script=/usr/bin/setxkbmap fr
```

Thx

**Comment by bloodyearth** [comment] 2018-09-30 22:31
I had a similar problem on Ubuntu.
I was helped by the complete removal of lighdm and reinstallation.

`sudo apt remove --purge lightdm`

Together with lightdm all greetings are deleted. Including slick-greeter.

Now, install lightdm again.

`sudo apt install lightdm`

After this, install slick-greeter.

I hope this helps, if you have not solved this problem yet.

P.S. Sorry for my bad english.

**Comment by leigh123linux** [comment] 2018-11-12 10:08
Maybe you should update to a supported version, slick-greeter-1.2.2

**Comment by darmeth** [comment] 2018-11-24 13:34
I'm using Fedora 29 with slick-greeter 1.2.2 and the issue still persists.

**Comment by ofuangka** [comment] 2018-11-27 04:20
I have the same issue on ArchLinux with 1.2.2.4.

**Comment by ofuangka** [comment] 2018-12-02 03:01
FYI, I haven't tested this thoroughly, but it seems to happen when an account in the group nopasswdlogin is selected by default when the greeter is loaded.  Can anyone else experiencing this confirm/disprove this?

**Comment by Tachiorz** [comment] 2018-12-14 14:44
I'm not using ldap, not in nopasswdlogin group. Password prompt vanishes when I leave computer overnight locked. Next morning I type in password blindly and it let me in.
slick-greeter  1.2.2 on Linux Mint 19 Tara

**Comment by mkauzlar** [comment] 2019-08-26 07:41
I experienced this issue from Mint 18 onward.
I have now installed Mint 19.2 with (which has slick-greeter/tina,now 1.2.7+tina amd64 [installed])
and the problem is still there.

**Comment by mkauzlar** [comment] 2019-12-06 08:11
This issue is still present in Mint 19.3 (slick-greeter 1.3.0+tricia)

**Comment by clefebvre** [comment] 2023-01-17 14:52
The screenshots are no longer accessible. I'll close this for now.

**Closed by clefebvre** 2023-01-17 14:52 UTC
Labels: bug
