### ISSUE TITLE
Password field issues

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/slick-greeter#194] opened 2021-10-27 10:35 UTC
```
 * slick-greeter version 1.5.4
 * Distribution - Alt Linux Sisyshpus
 * 64 bit
 ```

**Issue**
There are several issues related to password field
1. Slick greeter could show several fields to enter password
2. Password field could become invisible

**Steps to reproduce**
1. Press the button that shows a list of available Desktop Enviroments.
2. Return back.
3. Return steps 1-2 if required (for me it happened immediately).

After this steps slick greeter will show several password fields e.g. 

![a_lot_of_input_fields](https://user-images.githubusercontent.com/1499142/139049462-d0019b23-c0e3-4de0-8ddb-0f44de36e6be.png)

When this issue is reproduced and you enter the wrong passphrase then slick greeter will not show any password field at all e.g.

![no_input_field](https://user-images.githubusercontent.com/1499142/139049650-422b5147-3a40-49b5-963d-996558d85f68.png)

**Expected behaviour**
There is only one password field should be visible.

**Other information**
Probably, could be related to existing issues 
https://github.com/linuxmint/slick-greeter/issues/153
https://github.com/linuxmint/slick-greeter/issues/99

**Comment by leigh123linux** [comment] 2021-12-03 07:28
Duplicate of #153

**Closed by leigh123linux** 2021-12-03 07:28 UTC

**Comment by taquangtrung** [comment] 2025-04-02 02:57
I encountered the same issue. Has anyone managed to fix it?
