### ISSUE TITLE
Shutdown dialog missing buttons if other users are logged in

### ISSUE THREAD

**Issue by icarter09** [linuxmint/slick-greeter#145] opened 2019-12-08 15:57 UTC
```
 * slick-greeter version: 1.2.7
 * Distribution - Linux Mint 19.2
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 530
 * 64 bit
 ```

**Issue**
I want to shutdown a PC while another user is still logged in. I get this* message but cannot select an action. No button visible in the dialog.
* check image below

**Steps to reproduce**
Login with second user then lock screen and login with your user and shutdown your PC.This dialog pops up.

**Expected behaviour**
Exactly how it works now but with visible buttons for popup confirmation.

**Other information**
screenshot: https://user-images.githubusercontent.com/14105721/45628212-e2090180-ba93-11e8-9beb-0001a8ffca09.jpg

**Comment by icarter09** [comment] 2019-12-08 15:58
This ticket is to replace https://github.com/linuxmint/cinnamon/issues/7861.

@smurphos

**Comment by sdlins** [comment] 2020-01-11 16:47
I have the same problem. 

But before I had set `KillUserProcesses` to `yes` in `/etc/systemd/logind.conf` I stucked on splash screen of shutdown/restart and no real shutdown/restart would happen. 

Now, I see the same message of linuxmint/cinnamon#7861 without buttons.

**Comment by martinpescador** [comment] 2022-01-26 14:34
I can confirm that this bug is present in 20.3: Any user can shutdown the system even though other users are logged in.

**Comment by clefebvre** [comment] 2023-01-17 16:08
I'm going to close this as upstream because it's not slick-greeter which decides what's possible to do in terms of actions, it's LightDM (which itself probably relies on logind).

```
LightDM.get_can_suspend ()
LightDM.get_can_hibernate ()
LightDM.get_can_restart ()
LightDM.get_can_shutdown ()
```

The presence of logged in users is detected via Dbus. It results in the presence of the following message: "Other users are currently logged in to this computer, shutting down now will also close these other sessions.".

If LightDM says you can shutdown though, you can shutdown.

**Closed by clefebvre** 2023-01-17 16:08 UTC
Labels: bug
